### ISSUE TITLE
License file?

### ISSUE THREAD

**Issue by mhennerich** [radiosd/PlutoSdr#1]
This Python library looks really useful!
Do you mind adding a License file?

**Comment by radiosd** [comment]
Thank you for you encouragement and for the reminder about the license.  I am pretty new to such issues.

It does rely on using the python bindings for iio which I think means that I need to add the same Lesser GPL license (v2 I think)

I am traveling (just about to leave) but will be back in a couple of days and rectify this then.
regards Richard

**Comment by mhennerich** [comment]
Thanks!
