### ISSUE TITLE
SyntaxError in pluto_sdr.py line#375 "from oserr"

### ISSUE THREAD

**Issue by 3x10e8** [radiosd/PlutoSdr#4]
>> python setup.py install
```
byte-compiling C:\Python27\Lib\site-packages\pluto\pluto_sdr.py to pluto_sdr.pyc
  File "C:\Python27\Lib\site-packages\pluto\pluto_sdr.py", line 375
    raise OSError('failed to create an iio buffer') from oserr
                                                       ^
SyntaxError: invalid syntax
```
I just commented out from oserr. Alternatively, some formatting options could be  https://stackoverflow.com/questions/8978057/raising-builtin-exception-with-default-message-in-python

**Comment by radiosd** [comment]
You are right, it was an error, inadvertently capturing a  command entered for another window.  I did fix this. Thanks
